ALTER TABLE shop_config
  ADD COLUMN IF NOT EXISTS landing_hero_image_url    text,
  ADD COLUMN IF NOT EXISTS landing_hero_title        text,
  ADD COLUMN IF NOT EXISTS landing_hero_subtitle     text,
  ADD COLUMN IF NOT EXISTS landing_primary_color     text    NOT NULL DEFAULT '#0f172a',
  ADD COLUMN IF NOT EXISTS landing_carousel_enabled  boolean NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS landing_carousel_max_items integer NOT NULL DEFAULT 8,
  ADD COLUMN IF NOT EXISTS landing_carousel_title    text,
  ADD COLUMN IF NOT EXISTS landing_carousel_bg_color text    NOT NULL DEFAULT '#f1f5f9',
  ADD COLUMN IF NOT EXISTS landing_carousel_bg_image_url text,
  ADD COLUMN IF NOT EXISTS landing_testimonials_enabled  boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS landing_testimonials_title    text,
  ADD COLUMN IF NOT EXISTS landing_testimonials_data     jsonb,
  ADD COLUMN IF NOT EXISTS landing_testimonials_bg_color text    NOT NULL DEFAULT '#ffffff',
  ADD COLUMN IF NOT EXISTS landing_testimonials_bg_image_url text,
  ADD COLUMN IF NOT EXISTS landing_services_enabled  boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS landing_services_title    text,
  ADD COLUMN IF NOT EXISTS landing_services_subtitle text,
  ADD COLUMN IF NOT EXISTS landing_services_whatsapp text,
  ADD COLUMN IF NOT EXISTS landing_services_data     jsonb,
  ADD COLUMN IF NOT EXISTS landing_services_bg_color text    NOT NULL DEFAULT '#f8fafc',
  ADD COLUMN IF NOT EXISTS landing_services_bg_image_url text,
  ADD COLUMN IF NOT EXISTS landing_gallery_enabled  boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS landing_gallery_title    text,
  ADD COLUMN IF NOT EXISTS landing_gallery_subtitle text,
  ADD COLUMN IF NOT EXISTS landing_gallery_images   jsonb,
  ADD COLUMN IF NOT EXISTS landing_gallery_bg_color text    NOT NULL DEFAULT '#ffffff',
  ADD COLUMN IF NOT EXISTS landing_gallery_bg_image_url text,
  ADD COLUMN IF NOT EXISTS landing_contact_enabled  boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS landing_contact_title    text,
  ADD COLUMN IF NOT EXISTS landing_contact_subtitle text,
  ADD COLUMN IF NOT EXISTS landing_contact_address  text,
  ADD COLUMN IF NOT EXISTS landing_contact_phone    text,
  ADD COLUMN IF NOT EXISTS landing_contact_email    text,
  ADD COLUMN IF NOT EXISTS landing_contact_map_lat  float   NOT NULL DEFAULT -6.2088,
  ADD COLUMN IF NOT EXISTS landing_contact_map_lng  float   NOT NULL DEFAULT 106.8456,
  ADD COLUMN IF NOT EXISTS landing_contact_map_zoom integer NOT NULL DEFAULT 15,
  ADD COLUMN IF NOT EXISTS landing_contact_bg_color text    NOT NULL DEFAULT '#f8fafc',
  ADD COLUMN IF NOT EXISTS landing_contact_bg_image_url text;
